M48
; DRILL file {KiCad (6.0.5)} date Fri Jun 17 21:55:09 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-17T21:55:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.1244Y-4.0045
X4.1244Y-4.1955
T2
X4.0051Y-3.9927
X4.0051Y-4.2073
T0
M30
