M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 15:21:44 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-21T15:21:44-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.6556Y-3.6445
X7.6556Y-3.8355
T2
X7.7749Y-3.6327
X7.7749Y-3.8473
T0
M30
