M48
; DRILL file {KiCad (6.0.5)} date Sun Oct 23 12:56:46 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-23T12:56:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.0444Y-4.5645
X5.0444Y-4.7555
T2
X4.9251Y-4.5527
X4.9251Y-4.7673
T0
M30
